### ISSUE TITLE
Update More Information link

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-vs-testgenerator#11]
The more information link for the extension points to the wiki of this repo, but the main documentation seems to be in the readme.

Other extensions are mixed between if they point to the docs wiki, or the main page of the relevant repo. Not sure what would be preferable for this extension, but it would be good to switch it from pointing at wiki now more complete documentation exists.

**Comment by CharliePoole** [comment]
Alternatively, do we want to add it to the docs?

@rprouse Up to now this has been a sort of personal project of yours within the nunit org, so it kind of does its own thing. How do you want to treat it in the future?

**Comment by rprouse** [comment]
@CharliePoole it was @OsirisTerje that brought this project in. I just supported the idea and contributed some of the docs. I think the docs on the readme for this are a good start, but I think we should move the documentation out of this project's wiki into our main wiki and link to those docs from the readme. Should we close this wiki?

**Comment by CharliePoole** [comment]
Yes... let's do that. Can you create a docs issue to add a new section? I'm glad to do it, since the adding of new sections is a manual process. Just tell me what the right-hand menu should look like for this project. I'll put it together with blank pages somebody can then fill in.

Feel free to do it yourself as well. :-) It's just that I've been doing this a lot fairly recently and have it down to a routine.

**Comment by rprouse** [comment]
There isn't much to this project yet, so I am not sure we need sub-pages for this project, unless you want the short project blurb for the top page and then a quick start for the one sub-page. You could just split the current readme in two at the How to Use heading.

I really need to spend more time editing the docs. I will write the docs for the new `dotnet-test-nunit` I promise :smile:

**Comment by CharliePoole** [comment]
I created a new subdirectory with just the one page plus sidebar. Menus are restructured so as to group Visual Studio stuff together.

As you work on the docs, bear in mind that all renames and new pages (except in the root) require a cloned copy and a push. However, if you rename or create a page and it ends up in the root, the only loss is that it will not have the correct menu. You can fix that by pulling changes down to your local repo, doing the move an then pushing.

You also need to have a local copy if you want to edit the _Sidebar files, which all have to be edited in order to keep up the appearance of a tree that is opening branches. It's a bit tedious, I'm afraid.
