### ISSUE TITLE
Add the test adapter as part of the package

### ISSUE THREAD

**Issue by yowko** [nunit/nunit-vs-testgenerator#25]
Install nunit-vs-adapter and nunit3-vs-adapter automatically when install  nunit-vs-testgenerator.

**Comment by CharliePoole** [comment]
This seems to remove choice from the user. Suppose I don't want to use one of the adapters - or either one for that matter - but just want to generate tests?

**Comment by OsirisTerje** [comment]
There should be a choice in the UI, but we don't control that one.  And since we're moving more into using nuget adapters instead of vsix adapters it makes sense to add it.  Also, a vsix adapter will anyway overrule the nuget adapter.   I can ping the MS PG and ask if they would consider adding that as an option. 
I also think this is a good idea now,  assuming the majority wants this in - which of course are hard to say.
It is also a question of defaults.  Should it be with or without.   If it is without, you must manually add it,  if it is with, then you must manually delete it.  
But, if you use this extension, I would assume you do so because you like to "click the buttons" the lazy way, and then it makes sense to do as much as you can do.

**Comment by CharliePoole** [comment]
The choice I meant was whether to use the adapter at all. Shouldn't the test generator be entirely independent? Or am I misunderstanding something?

**Comment by OsirisTerje** [comment]
Microsoft themselves add the adapters to their own MSTest2 test generator extension.

**Comment by CharliePoole** [comment]
Sure, but Microsoft has a vested interest in folks running their tests in Visual Studio, while we are neutral.

Nevertheless, I can see the advantage of working like theirs and I'm not a user.

**Comment by OsirisTerje** [comment]
Yep, but then this is also a Visual Studio extension, so it kind of makes sense to include it here.  It can't run anywhere else.   The base functionality is anyway in VS, and making the different framework generator extensions behave the same makes sense.

**Comment by CharliePoole** [comment]
Yeah, I do get it and it doesn't really affect me. I do think that the description had to say clearly what's installed and when.

**Comment by OsirisTerje** [comment]
Good point!  I'll add that.
