### ISSUE TITLE
NUnit 3 tests using removed [ExpectedException]

### ISSUE THREAD

**Issue by nicholasudell** [nunit/nunit-vs-testgenerator#6]
When you generate a test using the NUnit 3 libraries and this extension, the test generator will add `[ExpectedException]` attributes  in the Test.g.cs files for any methods that have expected exceptions. `[ExpectedException]` was removed from NUnit 3, and so these files will fail to build.
## Steps to reproduce:
- Create a new class library
- Create a class as follows:

```
    public class Class
    {
        public void Method(object parameter)
        {
            if (parameter == null)
            {
                throw new ArgumentNullException(nameof(parameter));
            }
        }
    }
```
- Right-click the class, select "Create Intellitest"
- Choose "NUnit" as the framework
- Right-click the class, select "Run Intellitest".
- After intellitest finishes running, try to build.

An equivalent test.g.cs file will have been created, which fails to build because `ExpectedException` does not exist in the NUnit 3 libraries:

```
    public partial class ClassTest
    {

        [Test]
        [PexGeneratedBy(typeof(ClassTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void MethodTestThrowsArgumentNullException138()
        {
            Class s0 = new Class();
            this.MethodTest(s0, (object)null);
        }

        [Test]
        [PexGeneratedBy(typeof(ClassTest))]
        public void MethodTest685()
        {
            Class s0 = new Class();
            object s1 = new object();
            this.MethodTest(s0, s1);
            PexAssert.IsNotNull((object)s0);
        }
    }
```

See [SimpleNunitIntelliTest.zip](https://github.com/nunit/nunit-vs-testgenerator/files/146384/SimpleNunitIntelliTest.zip) for an example visual studio solution that exhibits this problem.

**Comment by CharliePoole** [comment]
@OsirisTerje ?

**Comment by OsirisTerje** [comment]
I'll bring this on to the Microsoft Test Group, we have no control over the attribute in the extension.

**Comment by CharliePoole** [comment]
It seems rather lame that they generate an arbitrary attribute without being told we support it!

**Comment by OsirisTerje** [comment]
Yes, and it should be something the extension should handle.  They should not make assumptions.

**Comment by codito** [comment]
It should be possible to stop emitting ExpectedException attribute by modifying `TryReadExpectedException` in [NUnitTestFramework.cs](https://github.com/nunit/nunit-vs-testgenerator/blob/master/IntelliTest.NUnit/NUnitTestFramework.cs#L157) to the following:

```
        public override bool TryReadExpectedException(ICustomAttributeProviderEx target, out TypeEx exceptionType)
        {
            exceptionType = null;
            return false;
        }
```

**Comment by OsirisTerje** [comment]
@codito Ok, so we can stop emitting it, but what happens with the functionality it is supposed to have?  Will this cause the Intellitest to complain about this all the time?  Whatare the negative effects of such a  change?

**Comment by CharliePoole** [comment]
@OsirisTerje This is what one of the things I feared when we took on this project. Trying to make something work correctly with a bunch of interfaces that the vendor holds closely to its chest and doesn't document puts us in a position of dealing with bugs we are technically responsible for but have no power to work with intelligently. It's what I went through with the vendor after spending a whole lot of time developing the NUnit Test Adapter - some questions couldn't even be answered without their first asking permission from management. I once believed we should maintain all the IDE adapters for products like VS, R#, etc. but the fact is that some vendors cooperation is limited to the brief period while they are trying to get you to do the project.

I hasten to say that this has nothing to do with folks who work for the vendor and who frequently try to help us. It's just that some companies encourage such helping behavior and make it easy for their employees, while others (no names here) create various institutional obstacles.

It has crossed my mind at times that we should simply **stop** providing various extenders and adapters for such products, or at least for those whose manuafacturers make it hard for us.

**Comment by OsirisTerje** [comment]
@CharliePoole I share your concern, but let us see if we are being followed up, currently we are.  The response I got back on this was also:
"Once this change is made, then IntelliTest’s codegen will change; it will emit a try/catch block around the generated test code that throws the exception (instead of decorating the generated test code with an ExpectedExceptin attribute). For e.g. in the case of xUnit.net here is how the generated test case would look like:"
I'll implement the suggested change, for the NUnit 3 generation. 
I would however like to see an interface that gave us more power over what is being generated.

**Comment by CharliePoole** [comment]
@OsirisTerje I remain dubious, but I agree we should see what happens. 

Since the answer you got was private, it's looks like the MS folks are not allowed to share info on this open channel. That in itself is not very encouraging. We don't have an MVP working on all pieces of our software and we shouldn't have to have one in order to get basic information.

BTW, I know I'm repeating what we have discussed privately.  That's by design. It's time to call out the lack of support publicly, I think.

**Comment by OsirisTerje** [comment]
@CharliePoole You're absolutely right,  and @codito above is a MSFT (according to his profile); but he should have added the full information, I see no reason why he could not.

**Comment by CharliePoole** [comment]
I'm pretty confident @codito is doing his best to help. Having worked at MS, I know that people are subject to various kinds of rules when they go online. Nevertheless, since we were encouraged to take over this bit of software by MS, one might expect them to encourage cooperation as a matter of policy.

**Comment by codito** [comment]
@CharliePoole @OsirisTerje sorry, I missed replying to this because of an incorrect assumption. I assumed it is OK to skip as the team was already involved with participants over email. There isn't a rule that discourages public participation or sharing of knowledge (it is the opposite in fact :)). This is my bad. Will do better next time.

@CharliePoole I agree with you around gaps in the documentation. We have the [extensibility APIs](https://msdn.microsoft.com/en-us/library/microsoft.pex.engine.testframeworks.attributebasedtestframeworkbase.aspx) documented in MSDN, we can add more examples, tutorials etc..

/cc:@pvlakshm

**Comment by OsirisTerje** [comment]
@codito @pvlakshm :  The extensibility API documentation is very vague, see https://msdn.microsoft.com/en-us/library/microsoft.pex.engine.testframeworks.testframeworkbase.aspx  , the parent of the link you gave, the descriptions of the properties and methods here are blank.  There is also needed some explanation of how this is meant to work, just class descriptions are a bit too little, so yes, overall intentional description, examples, etc would be nice
